attention_resolutions: 32,16,8
batch_size: 4
data_dir: ''
diffusion_steps: 1000
dropout: 0.0
ema_rate: '0.9999'
fp16_scale_growth: 0.001
data_root: 'data_root'

dataset_use: 'Xenium' # Visium NBME
SR_times: 5
gene_num: 25
save_interval: 1000

num_channels: 128
num_res_blocks: 1

learn_sigma: true
log_interval: 10
lr: 0.0001
lr_anneal_steps: 0
microbatch: -1
noise_schedule: linear
num_head_channels: 48
num_heads: 4
num_heads_upsample: -1
resblock_updown: true
use_scale_shift_norm: true
rescale_learned_sigmas: false
rescale_timesteps: false
resume_checkpoint: ''
schedule_sampler: uniform
timestep_respacing: ''
use_checkpoint: false
use_fp16: false
use_kl: false
predict_xstart: false
weight_decay: 0.00001
