attention_resolutions: 32,16,8
base_samples: ''
batch_size: 1
clip_denoised: True
data_dir: ''
dropout: 0.0

data_root: 'data_root'

dataset_use: 'Xenium' # Xenium Visium NBME
SR_times: 5
gene_num: 25
diffusion_steps: 1000
sampling_method: guided # guided

num_channels: 128
num_res_blocks: 1
model_path: logs/model.pt

learn_sigma: true
noise_schedule: linear
num_head_channels: 48
num_heads: 4
num_heads_upsample: -1
#num_samples: 50000
predict_xstart: false
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
timestep_respacing: '20'
use_checkpoint: false
use_fp16: false
use_kl: false
use_scale_shift_norm: true
